### ISSUE TITLE
Error in get (genname ,envir) . . 

### ISSUE THREAD

**Issue by jrhadams** [OnofriAndreaPG/lmDiallel#1]
Hey, many thanks for this project!

I just installed your package and it looks like everything works fine.

That said, I wanted to let you know that upon installing  you get this message

```r
> devtools::install_github("onofriAndreaPG/lmDiallel")
Error in get(genname, envir = envir) : object 'testthat_print' not found
Downloading GitHub repo onofriAndreaPG/lmDiallel@HEAD
```

it then proceeds to install successfully but it looks like that `object 'testthat_print'` error might be related to a specific version of testthat (see [here](https://github.com/r-lib/devtools/issues/2309#issuecomment-766483211))

**Comment by OnofriAndreaPG** [comment]
Thanks. I'll keep an eye on this; at the moment that message does not appear on my system. Regards -- Andrea

**Comment by jrhadams** [comment]
super :thumbsup:

**Comment by OnofriAndreaPG** [comment]
Dear jrhadams -- The problem you mention relates to the package testthat (see here: [https://github.com/r-lib/devtools/issues/2309](https://github.com/r-lib/devtools/issues/2309) and it is solved by installing the latter version for this package. Thanks for your message. Regards -- Andrea
