### ISSUE TITLE
Effects estimates

### ISSUE THREAD

**Issue by gsd050** [OnofriAndreaPG/lmDiallel#2]
Dear Andrea
I have been using the lmdiallel for analysis of half hybrid design.
I have issue with estimates calculated by different models used.
The summary function always lead to calculation of effects for n-1 genotypes where n is the number of genotypes.
Like for 6 parents it gives GCA only for 5, similarly for crosses when calculating SCA it excludes all effects from crosses involving last parent.
How could it be calculated using the other estimatess in hand

**Comment by OnofriAndreaPG** [comment]
Hello,

Thanks for your email. You can retrieve the full list of genetical parameters with the glht()function. An example is given in this page:

https://www.statforbiology.com/2021/stat_met_diallel_gardner/


Hope this is useful. All the best

Andrea
Il 21 mar 2021, 11:16 +0100, gsd050 ***@***.***>, ha scritto:

**Comment by OnofriAndreaPG** [comment]
This is a full example with Griffing's model (make sure you have the latest lmDiallel version):

data(lonnquist61)
dMod2 <- lm.diallel(Yield ~ Par1 + Par2,
                    data = lonnquist61, fct = "GRIFFING2")

gh <- glht(linfct = diallel.eff(dMod2))
summary(gh, test = adjusted(type = "none"))

**Comment by gsd050** [comment]
Thanks for a quick response.
It worked for GRIFFING2 as such. 
But it required updating the package for GE2 and GE3 models to work.
After the update, it worked like a charm.
