### ISSUE TITLE
diallel with missing phenotypes gives error : "Error in idx[i] <- y : replacement has length zero"

### ISSUE THREAD

**Issue by andtsouris** [OnofriAndreaPG/lmDiallel#4]
Hello Andrea,

I'm trying to use lm.diallel to calculate the GCA and SCA for a half diallel (with self crosses) between 26 parents where the phenotypes of about 5% of the crosses are missing. The missing values are not _NAs_ but the lines of those crosses are absent from the phenotypes dataframe.

When I try to run _lm.diallel(pheno ~ P1+P2, data=my_dat)_ I get the error : 
**Error in idx[i] <- y : replacement has length zero**.

The same error can be reproduced by removing the HxM cross from the lonnquist61 dataset.

Is there a way for us to avoid this error or adapt the _lm.diallel_ function to handle missing phenotypes?

Thanks for your help and for developing this useful package,
Andreas

**Comment by OnofriAndreaPG** [comment]
Hello Andreas,

at the moment the script does not handle missing genotypes... I think it could be modified to do so and I will put this on my agenda...

All the best

Andrea

**Comment by alexabaker526** [comment]
Hi Andrea,

Thank you for creating this package, it's been so useful! 

I wanted to second Andreas' comment, I also have data with missing crosses. Maybe the script could be modified to allow for a design matrix to be entered, or to be automatically generated, that accounts for the missing crosses. Or perhaps manually entering a matrix like this is already possible?

This paper describes a way of doing this in SAS:
Wu, H.X. & Matheson, A.C. (2020) Analysis of Half-diallel Mating Design with Missing Crosses: Theory and SAS Program for Testing and Estimating GCA and SCA Fixed Effects. Silvae Genetica, 49(3), 130-137.   

Thanks again!
Lexie

**Comment by OnofriAndreaPG** [comment]
I have implemented the method proposed in Wu and Matheson, by which it is now possible to fit the GRIFFING4 model to diallel experiments with mating scheme 4 and missing crosses. There must be at least one parent with no missing crosses. I was able to reproduce the results provided in Wu and Matheson, by using the code below.

Look forward to any comments.

Thanks 

Andrea

`
rm(list = ls())
library(tidyverse)
library(lmDiallel)
library(multcomp)
dataset <- read.csv("http://www.casaonofri.it/_datasets/radiata.csv")
head(dataset)
dataset <- dataset %>%
  pivot_longer(names_to = "Env", values_to = "Yield",
               cols = c(5:6)) %>%
  mutate(across(1:5, .fns = factor))
dataset <- dataset[is.na(dataset$Yield)!=T,]
head(dataset)

# Here we have unbalance (missing data) but no missing crosses
mod <- lm.diallel(Yield ~ I + J, data = dataset,
                  fct = "GRIFFING4", Env = Env,
                  Block = R)
gh <- glht(linfct = diallel.eff(mod, type = "means"))
summary(gh, test = adjusted(type = "none"))
anova(mod) # Type I
anova(mod, type = 3)

# Removing three crosses
datasetb <- dplyr::filter(dataset, !(I == "1" & J == "3") &
                !(I == "2" & J == "5") &
                !(I == "5" & J == "6"))

mod <- lm.diallel(Yield ~ I + J, data = datasetb,
                  fct = "GRIFFING4", Env = Env,
                  Block = R)
summary(mod)
gh <- glht(linfct = diallel.eff(mod, type = "means"))
summary(gh, test = adjusted(type = "none"))

anova(mod) # Type I
anova(mod, type = 3)

# Removing six crosses # Need to recode the factor
datasetc <- dplyr::filter(dataset, !(I == "1" & J == "3") &
                !(I == "1" & J == "5") &
                !(I == "2" & J == "5") &
                !(I == "3" & J == "5") &
                !(I == "4" & J == "5") &
                !(I == "5" & J == "6") )
datasetc <- mutate(datasetc, across(1:5, .fns = factor))
mod <- lm.diallel(Yield ~ I + J, data = datasetc,
                  fct = "GRIFFING4", Env = Env,
                  Block = R)
summary(mod)
gh <- glht(linfct = diallel.eff(mod, type = "means"))
summary(gh, test = adjusted(type = "none"))
anova(mod)
anova(mod, type = 3)

# Removing four crosses # Not possible! Need manual coding
datasetd <- dplyr::filter(dataset, !(I == "1" & J == "3") &
                !(I == "2" & J == "5") &
                !(I == "4" & J == "5") &
                !(I == "5" & J == "6") )
datasetd <- mutate(datasetd, across(1:5, .fns = factor))
mod <- lm.diallel(Yield ~ I + J, data = datasetd,
                  fct = "GRIFFING4", Env = Env,
                  Block = R)
`

**Comment by alexabaker526** [comment]
Andrea,

Thank you so much for testing this! I'm running your code above and I am getting an error, in the sections where 3 or 6 crosses are removed, the line: gh <- glht(linfct = diallel.eff(mod, type = "means")) gives the error code:

Error in temp2[, assign == i + 2] <- X : 
  number of items to replace is not a multiple of replacement length

I have the updated lmDiallel package installed. Any ideas?

Thanks again and really appreciate your help,
Lexie

**Comment by OnofriAndreaPG** [comment]
Hello Lexie
thanks for helping me to troubleshoot. I have run the code again in my Mac and it appears to work properly. Please note that the updated version is not yet on CRAN. Did you install the updated version from gitHub? Could I see the results of your sessionInfo(), please? Thanks a lot -- Andrea

**Comment by alexabaker526** [comment]
Andrea,

Ah! That was my problem, I had not updated from Github. Your code works for me now, thank you!

I am encountering an issue when running my own data with your code above. It is a Griffing4 diallel with 3 missing crosses in 2 of 4 environments. When I run a model with all 4 environments through the ghlt() function I get this error:

Error in glht.matrix(args, k) : 
#‘ncol(linfct)’ is not equal to ‘length(coef(model))’ 

However, I can run a model with the 2 environments that have a complete diallel separately and with the 2 environments that have missing crosses separately with no issues. Can the function be modified to allow for environments with missing crosses (with a design matrix accounting for them) to be analyzed together with environments with complete diallel? 

Here is code and data if useful:
[data_3_missing_crosses_1.csv](https://github.com/OnofriAndreaPG/lmDiallel/files/11163169/data_3_missing_crosses_1.csv)

#My data with three missing crosses:
#Half diallel, Griffing Model 4
#p = 6
#Env 1 and 2 are missing Hybrids 5, 11, 13 which are crosses (2 x 4), (1 x 4), (3 x 6) 
#Parent 5 is not missing any crosses, therefore design matrix should be possible
#Env 3 and 4 are not missing any crosses
#There is some imbalance (missing data) across Env

data <- read.csv("data_3_missing_crosses_1.csv", header=T)

data$I <- as.factor(data$I)
data$J <- as.factor(data$J)
data$Environment <- as.factor(data$Environment)
data$Replication <- as.factor(data$Replication)

mod <- lm.diallel(Value ~ I + J, data = data,
                  fct = "GRIFFING4", Env = Environment,
                  Block = Replication)
summary(mod)

gh <- glht(linfct = diallel.eff(mod, type = "means")) 

#Line 98 error:" Error in glht.matrix(args, k) : 
#‘ncol(linfct)’ is not equal to ‘length(coef(model))’ "

summary(gh, test = adjusted(type = "none")) 

anova(mod) # Type I
anova(mod, type = 3)

#filtering to environments 3 and 4 with complete diallel 

full <- data %>%
  filter(Environment == "3" | Environment == "4")

mod <- lm.diallel(Value ~ I + J, data = full,
                  fct = "GRIFFING4", Env = Environment,
                  Block = Replication)
summary(mod)

gh1 <- glht(linfct = diallel.eff(mod, type = "means")) 

summary(gh1, test = adjusted(type = "none")) 

anova(mod) # Type I
anova(mod, type = 3)

#filtering to just environments with missing crosses

miss<-data %>%
  filter(Environment == "1" | Environment == "2")

mod <- lm.diallel(Value ~ I + J, data = miss,
                  fct = "GRIFFING4", Env = Environment,
                  Block = Replication)
summary(mod)

gh1 <- glht(linfct = diallel.eff(mod, type = "means")) 

summary(gh1, test = adjusted(type = "none")) 

anova(mod) # Type I
anova(mod, type = 3)

**Comment by OnofriAndreaPG** [comment]
Dear Lexie,

thank you very much for helping me to debug this. By running our code I could discover several glitches that I have now corrected. Relating to the problem you mentioned with the ‘glht’ function, the error you noted is due to the fact that the incidence matrices for the different environments are, indeed, different, when one or more crosses are missing only in some environments and not in all of them. Due to the way the ‘diallel.eff()’ function was programmed, I could not find an easy way out of this; However, it is pretty easy to calculate the Expected Marginal Means for genetic effects and, to this aim, I coded the ‘emm.diallel()’ function: once you have fitted the model, you retrieve the genetic affects for all environments and pass the result to the ‘emm.diallel()’ function:

gh <- glht(linfct = diallel.eff(mod, type = "all"))
tmp <- summary(gh, test = adjusted(type = "none"))
dw <- emm.diallel(tmp)
dw

Obviously, the average genetic effects for the missing crosses cannot be estimated. One further possibility, when the interactions between genetic effects and the environments is not significant, you can fit a reduced model and retrieve the average genetic effects from there:

gh <- glht(linfct = diallel.eff(mod, type = "reduced"))
summary(gh, test = adjusted(type = "none”))

You can also regard the environment as random… but this is another story.

While I was playing with your data I have found that, inverting the parentals, (i.e. writing Value ~ J + I instead of Value ~ I + J) led to odd results and I have corrected a small buglet. Now this appears to be ok, but I have a question for you: when I fit the model 'Value ~ I + J’ and the model 'Value ~ male_1 + female_1’ I obtain different results for the environments with missing crosses. I noted that, in your dataset, the columns I and J do not match with the columns ‘male_1’ and ‘female_1’ and the two parentals are, often, swapped. I was just wondering what the relationship is between the two naming systems (if any) and whether this is a normal practice in your studies. Can you tell me something more about this, to help me fine tune the package? Thank you very much in advance (and sorry for this long email)

Andrea

**Comment by alexabaker526** [comment]
Andrea,

Wow, wonderful! Thank you! This is so great and works really well for me now. 

In regards to your question about the coding of the parents: I changed the way I coded the parents to make the code work after the update last month, to reflect the way Wu and Matheson had their data coded (With 6 parents: female 1 is crossed to all other 5 males, female 2 is crossed to 4 males, the female 3 is crossed to 3 males etc). Given that in a half diallel reciprocal effects are ignored, I figured this was OK and it was the only way the code would work at that time. Now, you have fixed that bug and I can use my original coding scheme, which reflects the actual direction of the cross (in the Hybrid column, with female listed first). Now, I obtain the same results for the genetic effects with both coding schemes, and using "I" and "J" or "female_1" and "male_1", in either direction in the model, and among any combination of environments. 

I found one error in the way I had coded the data I sent to you, apologies, that is likely the reason you were getting conflicting results. If it is useful, I am attaching the dataset with that error corrected (data_3_missing_crosses_1.csv), which has the Wu and Matheson coding scheme where cross direction is ignored. As well as the dataset with the second coding scheme (data_3_missing_crosses_2.csv), where the direction of the cross is reflected in the coding scheme (with parent Il101t as 1, C40 as 2, P39 as 3, Ia453 as 4, Ia5125 as 5, C68 as 6). The difference between the two data sets are the ways hybrids 3,4,5,7,8,15 are coded, they are flip flopped. Please let me know if any of this is unclear. Thanks so much for your help and for updating the package!

[data_3_missing_crosses_1.csv](https://github.com/OnofriAndreaPG/lmDiallel/files/11264718/data_3_missing_crosses_1.csv)
[data_3_missing_crosses_2.csv](https://github.com/OnofriAndreaPG/lmDiallel/files/11264719/data_3_missing_crosses_2.csv)

**Comment by alexabaker526** [comment]
Mistyped third to last sentence, should read: "The difference between the two data sets are the ways hybrids 3,4,5,8,9,15 are coded, they are flip flopped."

**Comment by OnofriAndreaPG** [comment]
Thank you very much for your help! I uploaded the new version to CRAN and, if you have other comments, please write!

Best

Andrea
